
version: '3.7'

services:
  mongodb:
    image: mongo
    restart: always
    expose:
      - 27017


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

  books:
    build: .
    ports:
      - 80:3000
    environment:
      - PORT=3000
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-todos_database}
      - DB_HOST=mongodb://mongodb:27017
    depends_on:
      - mongodb